// Code generated by goyacc parser.y. DO NOT EDIT.

//line parser.y:2
package LWH

import __yyfmt__ "fmt"

//line parser.y:2

var root node

//line parser.y:13
type yySymType struct {
	yys   int
	node  node
	token string
}

const CONTINUE = 57346
const PAUSE = 57347
const EXEC = 57348
const PATH = 57349
const HYPHEN = 57350
const ARROW = 57351
const ROUTE = 57352
const MKDISK = 57353
const SIZE = 57354
const UNIT = 57355
const NAME = 57356
const NUMBERN = 57357
const K = 57358
const M = 57359
const ID = 57360
const STRTYPE = 57361
const RMDISK = 57362
const FDISK = 57363
const ADD = 57364
const DELETE = 57365
const FIT = 57366
const TYPE = 57367
const B = 57368
const P = 57369
const E = 57370
const L = 57371
const BF = 57372
const FF = 57373
const WF = 57374
const FAST = 57375
const FULL = 57376

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"CONTINUE",
	"PAUSE",
	"EXEC",
	"PATH",
	"HYPHEN",
	"ARROW",
	"ROUTE",
	"MKDISK",
	"SIZE",
	"UNIT",
	"NAME",
	"NUMBERN",
	"K",
	"M",
	"ID",
	"STRTYPE",
	"RMDISK",
	"FDISK",
	"ADD",
	"DELETE",
	"FIT",
	"TYPE",
	"B",
	"P",
	"E",
	"L",
	"BF",
	"FF",
	"WF",
	"FAST",
	"FULL",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:117

const src = `exec path`

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 69

var yyAct = [...]int{
	61, 62, 58, 59, 60, 11, 55, 56, 57, 21,
	29, 24, 30, 65, 66, 53, 54, 8, 7, 3,
	28, 27, 26, 25, 4, 52, 51, 46, 49, 50,
	38, 14, 45, 5, 6, 10, 47, 19, 22, 11,
	64, 31, 63, 48, 15, 16, 17, 13, 44, 43,
	37, 42, 22, 41, 40, 39, 36, 35, 34, 32,
	33, 11, 20, 18, 12, 9, 2, 1, 23,
}

var yyPact = [...]int{
	13, -1000, -1000, 54, 32, 54, -2, -1000, -1000, 54,
	-1000, 50, 32, -1000, -1000, 49, 48, 47, 54, -1000,
	-2, -1000, -1000, -1000, 46, 45, 44, 42, 40, 39,
	23, -1000, 17, -1000, 28, 12, 8, -1000, -1000, -1,
	-21, -28, -33, 27, 25, -5, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int{
	0, 68, 67, 66, 65, 31, 64, 47, 63, 62,
	9,
}

var yyR1 = [...]int{
	0, 2, 2, 3, 3, 3, 3, 3, 3, 4,
	4, 6, 6, 8, 8, 9, 9, 10, 10, 10,
	10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
	10, 10, 7, 7, 7, 7, 7, 5, 5, 1,
	1,
}

var yyR2 = [...]int{
	0, 0, 1, 2, 2, 2, 2, 1, 1, 2,
	1, 2, 1, 2, 1, 2, 1, 1, 1, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 1, 3, 3, 3, 3, 3, 3, 3,
	3,
}

var yyChk = [...]int{
	-1000, -2, -3, 6, 11, 20, 21, 5, 4, -4,
	-5, 7, -6, -7, -5, 12, 13, 14, -8, -5,
	-9, -10, -5, -1, 13, 25, 24, 23, 22, 12,
	14, -5, 9, -7, 9, 9, 9, -5, -10, 9,
	9, 9, 9, 9, 9, 9, 10, 19, 15, 16,
	17, 18, 26, 16, 17, 27, 28, 29, 30, 31,
	32, 33, 34, 15, 15, 18, 19,
}

var yyDef = [...]int{
	1, -2, 2, 0, 0, 0, 0, 7, 8, 3,
	10, 0, 4, 12, 32, 0, 0, 0, 5, 14,
	6, 16, 17, 18, 0, 0, 0, 0, 0, 0,
	0, 9, 0, 11, 0, 0, 0, 13, 15, 0,
	0, 0, 0, 0, 0, 0, 37, 38, 33, 34,
	35, 36, 19, 30, 31, 20, 21, 22, 23, 24,
	25, 26, 27, 28, 29, 39, 40,
}

var yyTok1 = [...]int{
	1,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:56
		{
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:57
		{
			yyVAL.node = yyDollar[1].node
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:59
		{
			yyVAL.node = Node("EXEC", "exec").append(yyDollar[2].node)
			root = Node("EXEC", "exec").append(yyDollar[2].node)
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:60
		{
			yyVAL.node = Node("MKDISK", yyDollar[1].token).append(yyDollar[2].node)
			root = Node("MKDISK", yyDollar[1].token).append(yyDollar[2].node)
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:61
		{
			yyVAL.node = Node("RMDISK", yyDollar[1].token).append(yyDollar[2].node)
			root = Node("RMDISK", yyDollar[1].token).append(yyDollar[2].node)
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:62
		{
			yyVAL.node = Node("FDISK", yyDollar[1].token).append(yyDollar[2].node)
			root = Node("FDISK", yyDollar[1].token).append(yyDollar[2].node)
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:63
		{
			yyVAL.node = Node("PAUSE", yyDollar[1].token)
			root = Node("PAUSE", yyDollar[1].token)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:64
		{
			yyVAL.node = Node("COMANDO CONTINUAR", yyDollar[1].token)
			root = Node("COMANDO CONTINUAR", yyDollar[1].token)
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:67
		{
			yyVAL.node = yyDollar[1].node.append(yyDollar[2].node)
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:68
		{
			yyVAL.node.append(yyDollar[1].node)
		}
	case 11:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:70
		{
			yyVAL.node = yyDollar[1].node.append(yyDollar[2].node)
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:71
		{
			yyVAL.node.append(yyDollar[1].node)
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:73
		{
			yyVAL.node.append(yyDollar[1].node)
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:77
		{
			yyVAL.node = yyDollar[1].node.append(yyDollar[2].node)
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:78
		{
			yyVAL.node.append(yyDollar[1].node)
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:81
		{
			yyVAL.node = yyDollar[1].node
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:82
		{
			yyVAL.node = yyDollar[1].node
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:83
		{
			yyVAL.node = Node("UNIT", "B")
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:84
		{
			yyVAL.node = Node("TYPE", "P")
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:85
		{
			yyVAL.node = Node("TYPE", "E")
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:86
		{
			yyVAL.node = Node("TYPE", "L")
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:87
		{
			yyVAL.node = Node("FIT", "BF")
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:88
		{
			yyVAL.node = Node("FIT", "FF")
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:89
		{
			yyVAL.node = Node("FIT", "WF")
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:90
		{
			yyVAL.node = Node("DELETE", "FAST")
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:91
		{
			yyVAL.node = Node("DELETE", "FULL")
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:92
		{
			yyVAL.node = Node("ADD", yyDollar[3].token)
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:93
		{
			yyVAL.node = Node("SIZE", yyDollar[3].token)
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:94
		{
			yyVAL.node = Node("UNIT", "K")
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:95
		{
			yyVAL.node = Node("UNIT", "M")
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:99
		{
			yyVAL.node = yyDollar[1].node
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:100
		{
			yyVAL.node = Node("SIZE", yyDollar[3].token)
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:101
		{
			yyVAL.node = Node("UNIT", "K")
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:102
		{
			yyVAL.node = Node("UNIT", "M")
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:103
		{
			yyVAL.node = Node("NAME", yyDollar[3].token)
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:106
		{
			yyVAL.node = Node("PATH", yyDollar[3].token)
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:107
		{
			yyVAL.node = Node("PATH", yyDollar[3].token)
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:110
		{
			yyVAL.node = Node("NAME", yyDollar[3].token)
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:111
		{
			yyVAL.node = Node("NAME", yyDollar[3].token)
		}
	}
	goto yystack /* stack new state and value */
}
