// Code generated by goyacc parser.y. DO NOT EDIT.

//line parser.y:2
// analyzers Contiene los analizadores usados para la lectura inicial
package analyzers

import __yyfmt__ "fmt"

//line parser.y:3

import "MIA-PROYECTO1/lwh"

var Root lwh.Node

//line parser.y:14
type yySymType struct {
	yys   int
	node  lwh.Node
	token string
}

const PAUSE = 57346
const EXEC = 57347
const PATH = 57348
const HYPHEN = 57349
const ARROW = 57350
const ROUTE = 57351
const MKDISK = 57352
const SIZE = 57353
const UNIT = 57354
const NAME = 57355
const NUMBERN = 57356
const K = 57357
const M = 57358
const ID = 57359
const STRTYPE = 57360
const RMDISK = 57361
const FDISK = 57362
const ADD = 57363
const DELETE = 57364
const FIT = 57365
const TYPE = 57366
const B = 57367
const P = 57368
const E = 57369
const L = 57370
const BF = 57371
const FF = 57372
const WF = 57373
const FAST = 57374
const FULL = 57375
const MOUNT = 57376
const UNMOUNT = 57377
const IDM = 57378
const S_EQUAL = 57379
const COMMENT = 57380
const MKFS = 57381
const IDN = 57382
const MKFILE = 57383
const PCONT = 57384
const CONT = 57385
const LOGIN = 57386
const USER = 57387
const PWD = 57388
const LOGOUT = 57389
const MKDIR = 57390

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"PAUSE",
	"EXEC",
	"PATH",
	"HYPHEN",
	"ARROW",
	"ROUTE",
	"MKDISK",
	"SIZE",
	"UNIT",
	"NAME",
	"NUMBERN",
	"K",
	"M",
	"ID",
	"STRTYPE",
	"RMDISK",
	"FDISK",
	"ADD",
	"DELETE",
	"FIT",
	"TYPE",
	"B",
	"P",
	"E",
	"L",
	"BF",
	"FF",
	"WF",
	"FAST",
	"FULL",
	"MOUNT",
	"UNMOUNT",
	"IDM",
	"S_EQUAL",
	"COMMENT",
	"MKFS",
	"IDN",
	"MKFILE",
	"PCONT",
	"CONT",
	"LOGIN",
	"USER",
	"PWD",
	"LOGOUT",
	"MKDIR",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 151

var yyAct = [...]int{
	23, 66, 59, 42, 54, 19, 140, 28, 31, 57,
	136, 45, 32, 20, 55, 56, 60, 67, 44, 70,
	8, 4, 48, 46, 41, 135, 5, 132, 76, 125,
	31, 126, 127, 118, 119, 6, 7, 20, 115, 116,
	117, 124, 63, 138, 45, 30, 108, 68, 102, 69,
	10, 9, 139, 137, 11, 12, 46, 15, 93, 60,
	13, 97, 87, 14, 16, 85, 67, 101, 52, 134,
	88, 61, 133, 62, 64, 77, 20, 51, 129, 130,
	50, 38, 33, 39, 112, 113, 114, 22, 131, 110,
	111, 37, 36, 35, 34, 103, 49, 122, 123, 109,
	106, 107, 128, 121, 104, 20, 120, 105, 20, 72,
	24, 25, 26, 100, 99, 39, 98, 96, 95, 94,
	92, 91, 90, 89, 86, 84, 83, 82, 81, 80,
	79, 78, 75, 74, 73, 71, 20, 3, 65, 53,
	17, 58, 47, 40, 43, 29, 27, 21, 18, 2,
	1,
}

var yyPact = [...]int{
	16, -1000, 16, -1000, 130, 99, 130, 70, -1000, -33,
	102, -1000, 56, -31, -1000, 31, 7, -1000, 130, -1000,
	127, 99, -1000, -1000, 126, 125, 124, 130, -1000, 70,
	-1000, -1000, -1000, 123, 122, 121, 120, 119, 118, 117,
	-33, -1000, 116, 102, -1000, -1000, -1000, 56, -1000, 115,
	114, 113, 112, -31, -1000, 111, 110, 109, 31, -1000,
	-1000, 108, -1000, 106, 105, 7, -1000, -1000, 40, -1000,
	-1000, 86, -1000, 93, 85, 29, -1000, -1000, 74, 58,
	9, 1, 92, 89, 80, -1000, 24, -1000, -1000, 12,
	-1, 88, 63, -1000, 10, 55, 8, -1000, -7, 39,
	34, -1000, -11, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000,
}

var yyPgo = [...]int{
	0, 12, 150, 137, 149, 148, 0, 147, 87, 146,
	145, 45, 144, 18, 143, 24, 142, 22, 141, 2,
	139, 4, 138, 1,
}

var yyR1 = [...]int{
	0, 2, 4, 4, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 5, 5, 7,
	7, 9, 9, 10, 10, 12, 12, 14, 14, 16,
	16, 20, 20, 18, 18, 22, 22, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 17, 17, 17, 17, 17, 17, 17, 21,
	21, 21, 21, 19, 19, 19, 19, 19, 19, 23,
	23, 23, 13, 13, 15, 8, 8, 8, 8, 8,
	6, 6, 1, 1,
}

var yyR2 = [...]int{
	0, 1, 2, 1, 2, 2, 2, 2, 1, 2,
	2, 1, 2, 2, 1, 2, 2, 2, 1, 2,
	1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
	1, 2, 1, 2, 1, 2, 1, 1, 1, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 1, 3, 1, 3, 3, 3, 1,
	3, 1, 1, 1, 3, 1, 3, 3, 3, 3,
	3, 3, 3, 3,
}

var yyChk = [...]int{
	-1000, -2, -4, -3, 5, 10, 19, 20, 4, 35,
	34, 38, 39, 44, 47, 41, 48, -3, -5, -6,
	6, -7, -8, -6, 11, 12, 13, -9, -6, -10,
	-11, -6, -1, 12, 24, 23, 22, 21, 11, 13,
	-14, -15, 36, -12, -13, -6, -1, -16, -17, 40,
	24, 21, 12, -20, -21, 45, 46, 40, -18, -19,
	-6, 40, 42, 11, 43, -22, -23, -6, 40, 42,
	-6, 8, -8, 8, 8, 8, -6, -11, 8, 8,
	8, 8, 8, 8, 8, -15, 8, -13, -17, 8,
	8, 8, 8, -21, 8, 8, 8, -19, 8, 8,
	8, -23, 8, 9, 18, 14, 15, 16, 17, 25,
	15, 16, 26, 27, 28, 29, 30, 31, 32, 33,
	14, 14, 17, 18, 17, 17, 32, 33, 14, 15,
	16, 25, 17, 17, 14, 17, 17, 14, 9, 18,
	17,
}

var yyDef = [...]int{
	0, -2, 1, 3, 0, 0, 0, 0, 8, 0,
	0, 11, 0, 0, 14, 0, 0, 2, 4, 18,
	0, 5, 20, 75, 0, 0, 0, 6, 22, 7,
	24, 37, 38, 0, 0, 0, 0, 0, 0, 0,
	9, 28, 0, 10, 26, 72, 73, 12, 30, 0,
	0, 0, 0, 13, 32, 0, 0, 0, 15, 34,
	63, 0, 65, 0, 0, 16, 36, 69, 0, 71,
	17, 0, 19, 0, 0, 0, 21, 23, 0, 0,
	0, 0, 0, 0, 0, 27, 0, 25, 29, 0,
	0, 0, 0, 31, 0, 0, 0, 33, 0, 0,
	0, 35, 0, 80, 81, 76, 77, 78, 79, 39,
	50, 51, 40, 41, 42, 43, 44, 45, 46, 47,
	48, 49, 82, 83, 74, 52, 53, 54, 55, 56,
	57, 58, 59, 60, 61, 62, 64, 66, 67, 68,
	70,
}

var yyTok1 = [...]int{
	1,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:98
		{
			yyVAL.node = yyDollar[1].node
			Root = yyVAL.node
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:100
		{
			yyVAL.node = yyDollar[1].node.Append(yyDollar[2].node)
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:101
		{
			yyVAL.node.Append(yyDollar[1].node)
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:103
		{
			yyVAL.node = lwh.NodeF("EXEC", yyDollar[1].token).Append(yyDollar[2].node)
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:104
		{
			yyVAL.node = lwh.NodeF("MKDISK", yyDollar[1].token).Append(yyDollar[2].node)
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:105
		{
			yyVAL.node = lwh.NodeF("RMDISK", yyDollar[1].token).Append(yyDollar[2].node)
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:106
		{
			yyVAL.node = lwh.NodeF("FDISK", yyDollar[1].token).Append(yyDollar[2].node)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:107
		{
			yyVAL.node = lwh.NodeF("PAUSE", yyDollar[1].token)
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:108
		{
			yyVAL.node = lwh.NodeF("UNMOUNT", yyDollar[1].token).Append(yyDollar[2].node)
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:109
		{
			yyVAL.node = lwh.NodeF("MOUNT", yyDollar[1].token).Append(yyDollar[2].node)
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:110
		{
			yyVAL.node = lwh.NodeF("COMENTARIO", yyDollar[1].token)
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:111
		{
			yyVAL.node = lwh.NodeF("MKFS", yyDollar[1].token).Append(yyDollar[2].node)
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:112
		{
			yyVAL.node = lwh.NodeF("LOGIN", yyDollar[1].token).Append(yyDollar[2].node)
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:113
		{
			yyVAL.node = lwh.NodeF("LOGOUT", yyDollar[1].token)
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:114
		{
			yyVAL.node = lwh.NodeF("MKFILE", yyDollar[1].token).Append(yyDollar[2].node)
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:115
		{
			yyVAL.node = lwh.NodeF("MKDIR", yyDollar[1].token).Append(yyDollar[2].node)
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:117
		{
			yyVAL.node = yyDollar[1].node.Append(yyDollar[2].node)
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:118
		{
			yyVAL.node.Append(yyDollar[1].node)
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:120
		{
			yyVAL.node = yyDollar[1].node.Append(yyDollar[2].node)
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:121
		{
			yyVAL.node.Append(yyDollar[1].node)
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:123
		{
			yyVAL.node = yyDollar[1].node.Append(yyDollar[2].node)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:124
		{
			yyVAL.node.Append(yyDollar[1].node)
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:126
		{
			yyVAL.node = yyDollar[1].node.Append(yyDollar[2].node)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:127
		{
			yyVAL.node.Append(yyDollar[1].node)
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:129
		{
			yyVAL.node = yyDollar[1].node.Append(yyDollar[2].node)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:130
		{
			yyVAL.node.Append(yyDollar[1].node)
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:132
		{
			yyVAL.node = yyDollar[1].node.Append(yyDollar[2].node)
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:133
		{
			yyVAL.node.Append(yyDollar[1].node)
		}
	case 29:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:135
		{
			yyVAL.node = yyDollar[1].node.Append(yyDollar[2].node)
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:136
		{
			yyVAL.node.Append(yyDollar[1].node)
		}
	case 31:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:138
		{
			yyVAL.node = yyDollar[1].node.Append(yyDollar[2].node)
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:139
		{
			yyVAL.node.Append(yyDollar[1].node)
		}
	case 33:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:141
		{
			yyVAL.node = yyDollar[1].node.Append(yyDollar[2].node)
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:142
		{
			yyVAL.node.Append(yyDollar[1].node)
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:144
		{
			yyVAL.node = yyDollar[1].node.Append(yyDollar[2].node)
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:145
		{
			yyVAL.node.Append(yyDollar[1].node)
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:147
		{
			yyVAL.node = yyDollar[1].node
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:148
		{
			yyVAL.node = yyDollar[1].node
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:149
		{
			yyVAL.node = lwh.NodeF("UNIT", yyDollar[3].token)
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:150
		{
			yyVAL.node = lwh.NodeF("TYPE", yyDollar[3].token)
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:151
		{
			yyVAL.node = lwh.NodeF("TYPE", yyDollar[3].token)
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:152
		{
			yyVAL.node = lwh.NodeF("TYPE", yyDollar[3].token)
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:153
		{
			yyVAL.node = lwh.NodeF("FIT", yyDollar[3].token)
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:154
		{
			yyVAL.node = lwh.NodeF("FIT", yyDollar[3].token)
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:155
		{
			yyVAL.node = lwh.NodeF("FIT", yyDollar[3].token)
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:156
		{
			yyVAL.node = lwh.NodeF("DELETE", yyDollar[3].token)
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:157
		{
			yyVAL.node = lwh.NodeF("DELETE", yyDollar[3].token)
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:158
		{
			yyVAL.node = lwh.NodeF("ADD", yyDollar[3].token)
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:159
		{
			yyVAL.node = lwh.NodeF("SIZE", yyDollar[3].token)
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:160
		{
			yyVAL.node = lwh.NodeF("UNIT", yyDollar[3].token)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:161
		{
			yyVAL.node = lwh.NodeF("UNIT", yyDollar[3].token)
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:164
		{
			yyVAL.node = lwh.NodeF("ID", yyDollar[3].token)
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:165
		{
			yyVAL.node = lwh.NodeF("TYPE", yyDollar[3].token)
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:166
		{
			yyVAL.node = lwh.NodeF("TYPE", yyDollar[3].token)
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:167
		{
			yyVAL.node = lwh.NodeF("ADD", yyDollar[3].token)
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:168
		{
			yyVAL.node = lwh.NodeF("UNIT", yyDollar[3].token)
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:169
		{
			yyVAL.node = lwh.NodeF("UNIT", yyDollar[3].token)
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:170
		{
			yyVAL.node = lwh.NodeF("UNIT", yyDollar[3].token)
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:173
		{
			yyVAL.node = lwh.NodeF("USER", yyDollar[3].token)
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:174
		{
			yyVAL.node = lwh.NodeF("PWD", yyDollar[3].token)
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:175
		{
			yyVAL.node = lwh.NodeF("PWD", yyDollar[3].token)
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:176
		{
			yyVAL.node = lwh.NodeF("ID", yyDollar[3].token)
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:178
		{
			yyVAL.node = yyDollar[1].node
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:179
		{
			yyVAL.node = lwh.NodeF("ID", yyDollar[3].token)
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:180
		{
			yyVAL.node = lwh.NodeF("P", yyDollar[1].token)
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:181
		{
			yyVAL.node = lwh.NodeF("SIZE", yyDollar[3].token)
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:182
		{
			yyVAL.node = lwh.NodeF("CONT", yyDollar[3].token)
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:183
		{
			yyVAL.node = lwh.NodeF("CONT", yyDollar[3].token)
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:186
		{
			yyVAL.node = yyDollar[1].node
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:187
		{
			yyVAL.node = lwh.NodeF("ID", yyDollar[3].token)
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:188
		{
			yyVAL.node = lwh.NodeF("P", yyDollar[1].token)
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:191
		{
			yyVAL.node = yyDollar[1].node
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:192
		{
			yyVAL.node = yyDollar[1].node
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:194
		{
			yyVAL.node = lwh.NodeF("ID", yyDollar[3].token)
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:196
		{
			yyVAL.node = yyDollar[1].node
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:197
		{
			yyVAL.node = lwh.NodeF("SIZE", yyDollar[3].token)
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:198
		{
			yyVAL.node = lwh.NodeF("UNIT", yyDollar[3].token)
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:199
		{
			yyVAL.node = lwh.NodeF("UNIT", yyDollar[3].token)
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:200
		{
			yyVAL.node = lwh.NodeF("NAME", yyDollar[3].token)
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:202
		{
			yyVAL.node = lwh.NodeF("PATH", yyDollar[3].token)
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:203
		{
			yyVAL.node = lwh.NodeF("PATH", yyDollar[3].token)
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:205
		{
			yyVAL.node = lwh.NodeF("NAME", yyDollar[3].token)
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:206
		{
			yyVAL.node = lwh.NodeF("NAME", yyDollar[3].token)
		}
	}
	goto yystack /* stack new state and value */
}
